layout: {zmk_keyboard: forager}
layers:
  BASE:
    - Q
    - W
    - E
    - R
    - T
    - Y
    - U
    - I
    - O
    - P
    - {t: A, h: ⌃}
    - {t: S, h: ⌥}
    - {t: D, h: ⌘}
    - {t: F, h: ⇧}
    - {t: G, h: ✦}
    - {t: H, h: ✦}
    - {t: J, h: ⇧}
    - {t: K, h: ⌘}
    - {t: L, h: ⌥}
    - {t: ;, h: ⌃}
    - Z
    - X
    - C
    - V
    - B
    - N
    - M
    - ','
    - .
    - /
    - {t: ␣, h: NAV}
    - {t: ⇥, h: NUM}
    - {t: ⌫, h: FUN}
    - {t: ␣, h: BRAC}
  NAV:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ⇱
    - ⇟
    - ⇞
    - ⇲
    - ⌃
    - ⌥
    - ⌘
    - ⇧
    - ⌃⌥⇧⌘
    - ''
    - ←
    - ↓
    - ↑
    - →
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - {type: held}
    - ''
    - ⌫
    - ␣
  NUM:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - '7'
    - '8'
    - {t: '9', s: '='}
    - '-'
    - ⌃
    - ⌥
    - ⌘
    - ⇧
    - ⌃⌥⇧⌘
    - ''
    - '4'
    - '5'
    - '6'
    - +
    - ''
    - ''
    - ''
    - ''
    - ''
    - {t: '0', s: '~'}
    - '1'
    - '2'
    - '3'
    - \
    - ''
    - {type: held}
    - ⌫
    - ␣
  BRAC:
    - ''
    - ''
    - (
    - )
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - <
    - '>'
    - '{'
    - '}'
    - ''
    - (RA(RC(RGUI)))
    - ⇧
    - ⌘
    - ⌥
    - ⌃
    - ''
    - ''
    - '['
    - ']'
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ␣
    - ⇥
    - ''
    - {type: held}
  FUN:
    - F12
    - F7
    - F8
    - F9
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - F11
    - F4
    - F5
    - F6
    - ''
    - (RA(RC(RGUI)))
    - ⇧
    - ⌘
    - ⌥
    - ⌃
    - F10
    - F1
    - F2
    - F3
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ␣
    - ⇥
    - {type: held}
    - ''
  Combos: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
    '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
combos:
  - p: [10, 11]
    k: {t: ⎋, h: ⌃⌥}
    l:
      - Combos
  - p: [12, 13]
    k: {t: ⇥, h: ⇧⌘}
    l:
      - Combos
  - p: [16, 17]
    k: {t: ⏎, h: ⇧⌘}
    l:
      - Combos
  - p: [17, 18]
    k: {t: ⌫, h: ⇧⌘}
    l:
      - Combos
  - p: [26, 27]
    k: ← □
    l:
      - Combos
  - p: [27, 28]
    k: □ →
    l:
      - Combos
  - p: [6, 7]
    k: Back
    l:
      - Combos
  - p: [7, 8]
    k: Forward
    l:
      - Combos
  - p: [22, 23]
    k: Copy
    l:
      - Combos
  - p: [21, 23]
    k: Paste
    a: bottom
    o: 0.1
    s: -0.3
    l:
      - Combos
  - p: [21, 22]
    k: Cut
    l:
      - Combos
  - p: [20, 21]
    k: Undo
    l:
      - Combos
  - p: [20, 21, 22]
    k: Redo
    a: bottom
    o: 0.6
    l:
      - Combos
  - p: [4, 5]
    k: Studio
    l:
      - Combos
  - p: [0, 1]
    k: '`'
    l:
      - Combos
  - p: [8, 9]
    k: ''''
    l:
      - Combos
  - p: [21, 22, 23]
    k: Clipboard
    l: [Combos]
    a: bottom
    o: 0.6
  - p: [26, 27, 28]
    k: Screenshot
    l: [Combos]
    a: bottom
    o: 0.6
