---
include:
  - board: xiao_ble/nrf52840/zmk
    shield: forager_left rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
  - board: xiao_ble/nrf52840/zmk
    shield: forager_right rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
  - board: xiao_ble/nrf52840/zmk
    shield: forager_central_dongle
    cmake-args: -DCONFIG_ZMK_STUDIO=n -DCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
    artifact-name: forager_central_dongle_oled
  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
    artifact-name: settings_reset_xiao_ble
  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
    artifact-name: settings_reset_nice_nano